### ISSUE TITLE
this app does not generate tvOS icons 

### ISSUE THREAD

**Issue by octopicorn** [onmyway133/IconGenerator#15]
Steps to reproduce:
- drag png into square
- select `tvOS` radio
- click generatebutton

Expected
- new appiconset with tvOS images

Actual
- new appiconset with no images and Contents.json with the following body:
```
{
  "images" : [],
  "info" : {
    "version" : 1,
    "author" : "xcode"
  }
}
```

**Comment by onmyway133** [comment]
@octopicorn Hi, this app does not generate tvOS for now, I 've removed that from the option list

**Comment by octopicorn** [comment]
Thank you!
