### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by n0n1** [onmyway133/IconGenerator#2]
Hi, @onmyway133 Do you plan add new features for this app? android support?

**Comment by onmyway133** [comment]
@n0n1 Hi, I guess you can use https://developer.android.com/studio/write/image-asset-studio.html ?

Let me know if you have any suggestions on features?

**Comment by n0n1** [comment]
@onmyway133 Will be very convenient, if a tool will be have a feature create android icons too.
Some a designers (with low level) will be can create all icons from a few files (1,2). 
ps. I know about Image Asset Studio, but before you need install Android Studio.

**Comment by n0n1** [comment]
@onmyway133 Some developers using another tools. Visual Studio, Appcelerator Studio, Atom etc.

**Comment by onmyway133** [comment]
@n0n1 Hi, I see there 's https://github.com/romannurik/AndroidAssetStudio. I will make one if I see the need. Thanks for your suggestions ❤️

**Comment by onmyway133** [comment]
@n0n1 Hi, what do you use to generate different sizes for an image, I read https://stackoverflow.com/questions/19196616/is-there-a-way-to-create-xxhdpi-xhdpi-hdpi-mdpi-and-ldpi-drawables-from-a-lar and people seem to use different tools. I use Android Studio Image Asset but it is for icon or notification only
