### ISSUE TITLE
support linux ？

### ISSUE THREAD

**Issue by jingle0927** [onmyway133/IconGenerator#4]

**Comment by onmyway133** [comment]
@jingle0927 Hi, technically this can be built for macOS, Linux and Windows. I will try to make builds soon

**Comment by jingle0927** [comment]
@onmyway133  thanks

**Comment by onmyway133** [comment]
@jingle0927 Hi, can you check the linux distribution here https://github.com/onmyway133/IconGenerator/releases/tag/1.0.0 ?

**Comment by jingle0927** [comment]
@onmyway133  I will check it  thanks

**Comment by onmyway133** [comment]
@jingle0927 Hi, I had this problem and fixed for macOS. Not sure how to fix for Linux as the underlying problem lies in https://github.com/electron-userland/electron-packager

**Comment by jingle0927** [comment]
ok
