### ISSUE TITLE
Question: Why node_modules is included?

### ISSUE THREAD

**Issue by Jackymancs4** [onmyway133/IconGenerator#5]
Hello @onmyway133 

Can I know why this line https://github.com/onmyway133/IconGenerator/blob/1ae5b0485f35d2b1887f1fa9a2b44fefb13b46a8/.gitignore#L21 is commented?

Including node_modules in the repo greatly increases its weight, and as far as I know is considered bad practice.

**Comment by onmyway133** [comment]
@Jackymancs4 Hi, I don't have a strong opinion about this. I want to track in git dependencies I don't have control. It seems most people agree not to track `node_modules` in git https://devcenter.heroku.com/articles/node-best-practices#only-git-the-important-bits

**Comment by Jackymancs4** [comment]
I see. Thanks for the insights.
I wanted to be sure you didn't included it for technical reasons since I updated almost every dependency on my build.

> It seems most people agree not to track node_modules in git

Indeed, I always considered the lock file (```yarn.lock```) the right way to enforce depencency consistency
