### ISSUE TITLE
Follow Human Interface Guidelines iOS

### ISSUE THREAD

**Issue by NatoBoram** [onmyway133/IconGenerator#6]
Hello!

There's a mention in the ReadMe.md that says *Follow Human Interface Guidelines iOS*. After I've tried with a plain icon, I found it it wasn't true at all : It just takes an icon and outputs the appropriate sizes. Which is great, but not what is in the ReadMe.

As such, I'd like to request assistance in following the guidelines given a simple logo with a set of simple options.

Here's the optional features that would help users respect the guidelines with minimal effort.

* Generate a coloured background behind icons
* Add a customizable padding around icons

With this, I believe users of this application would be able to generate their iOS images and their Android images from the same logo and still respect both Material Design and Cupertino guidelines.

Have a nice day!

**Comment by onmyway133** [comment]
@NatoBoram Hi, what I mean by following HIG is about the icon sizes for each platform. Colored background and padding are nice to have, but I'm busy these days so I don't think if I can make it. PRs for these features are always welcome
