### ISSUE TITLE
Issue with tvOS

### ISSUE THREAD

**Issue by hadihashem** [onmyway133/IconGenerator#8]
Hello @onmyway133 
I'm facing an issue trying to generate tvOS icons from this file
![example](https://user-images.githubusercontent.com/34154847/43999470-20049e16-9e0d-11e8-96fa-9163dc996f3e.png)
I get an empty Assets forlder
It is working well however with the other types iOS and macOS
Please advise
Regards

**Comment by onmyway133** [comment]
@hadihashem Hi, thanks for reporting, I will check

**Comment by hadihashem** [comment]
Hi  @onmyway133 
After investigation, the file Contents.json doesn't contain any dimension specification about tvOS
And also, within the file Generator.js 
![2018-08-12_142439](https://user-images.githubusercontent.com/34154847/44001951-785b4f5a-9e3b-11e8-849d-2798a4ee9c75.jpg)

**Comment by onmyway133** [comment]
@hadihashem Hi, do you use Xcode 9 or Xcode 10? The template I'm using now is from Xcode 9

**Comment by hadihashem** [comment]
Hi @onmyway133 
I'm using Xcode 9 but as mentionned earlier, the current template is not tvOS ready

**Comment by onmyway133** [comment]
@hadihashem Hi, it was my intention. tvOS app icons differ from iOS and macOS in that it has many kinds of icons. How do you want IconGenerator to support it?

![tv](https://user-images.githubusercontent.com/2284279/44152270-5f3272f8-a0a5-11e8-876b-2cb0968b2c19.png)

**Comment by hadihashem** [comment]
@onmyway133 there are solutions for everything but if this feature is not included in the Application today then I would suggest to take off the tvOS option from the GUI
It is confusing otherwise
![2018-08-16_070541](https://user-images.githubusercontent.com/34154847/44189327-19962e00-a123-11e8-9348-260f39fb83d3.jpg)

**Comment by onmyway133** [comment]
@hadihashem Hi, I will remove tvOS support for now
